[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

# Ignore flat-layout.
[tool.setuptools]
py-modules = []

[project]
name = "pybuildingenergy"
version = "2.0.3"
description = "Energy Simulation of building using EN ISO 52000, EN ISO 15316, EN ISO 16798, EN ISO 12831, and more"
license = "BSD-3-Clause"
license-files = ["LICENSE.md"]
readme = "Readme.md"
requires-python = ">=3.11.0"
authors = [{name = "Daniele Antonucci", email = "daniele.antonucci@eurac.edu"}, {name = "Ulrich Filippi Oberegger", email = "ulrich.filippi@eurac.edu"}]
maintainers = [{name = "Daniele Antonucci", email = "daniele.antonucci@eurac.edu"}]
keywords = [
    "energy",
    "building",
    "heating and cooling",
    "52016",
    "EPBD",
]

dependencies = [
    "holidays>=0.81",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "pvlib>=0.13.0",
    "pyecharts>=2.0.9",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
    "timezonefinder>=8.1.0",
    "tqdm>=4.67.1",
    "workalendar>=17.0.0"
]

classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  
  "Development Status :: 4 - Beta",
  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "Operating System :: Unix",
  "Operating System :: POSIX",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development :: Build Tools"
]


[project.urls]
Homepage = "https://github.com/EURAC-EEBgroup/pyBuildingEnergy"
Documentation = "https://pybuildingenergy.readthedocs.io/en/latest/Overview/overview.html"
Repository = "https://github.com/EURAC-EEBgroup/pyBuildingEnergy"
Issues = "https://github.com/EURAC-EEBgroup/pyBuildingEnergy/issues"
Changelog = "https://github.com/EURAC-EEBgroup/pyBuildingEnergy/blob/master/CHANGELOG.rst"

[project.optional-dependencies]
gui = []
cli = []
dev = [
  "coverage>=7.5",
  "bump2version>=1.0.1",
  "pytest==9.0.1",
]


[tool.pytest.ini_options]
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  ]

[tool.setuptools.package-data]
pybuildingenergy = [
  "archetypes.pickle",
  "assets/*.png",
  "charts/*.html",
  "charts/assets/*.js",
  "data/*.json",
  "data/*.md",
  "source/*.md",
]

[tool.setuptools.exclude-package-data]
pybuildingenergy = ["Result/*"]
