from __future__ import annotations

import pandas as pd


def get_example_hvac_input() -> dict:
    return {
        "emitter_type": "Floor heating",
        "nominal_power": 15.0,
        "emission_efficiency": 90.0,
        "flow_temp_control_type": "Type 2 - Based on outdoor temperature",
        "selected_emm_cont_circuit": 0,
        "mixing_valve": True,
        "emission_calculation_mode": "en15316-2",
        "emission_time_step_hours": 1.0,
        "mixing_valve_delta": 2,
        "emission_15316_2_config": {
            "time_step_hours": 1.0,
            "demand_unit": "kWh",
            "default_heating_internal_temperature_C": 20.0,
            "default_cooling_internal_temperature_C": 26.0,
            "heating": {
                "stratification_K": 0.0,
                "control_K": 0.0,
                "radiation_K": 0.0,
                "hydraulic_balancing_K": 0.0,
                "room_automation_K": 0.0,
                "embedded_K": 0.0,
                "nominal_power_kW": 15.0,
                "fan_power_W": 0.0,
                "fan_count": 0,
                "control_power_W": 0.0,
                "control_count": 0,
                "convective_fraction": 0.7,
            },
            "cooling": {
                "stratification_K": 0.0,
                "control_K": 0.0,
                "radiation_K": 0.0,
                "hydraulic_balancing_K": 0.0,
                "room_automation_K": 0.0,
                "embedded_K": 0.0,
                "nominal_power_kW": 15.0,
                "fan_power_W": 0.0,
                "fan_count": 0,
                "control_power_W": 0.0,
                "control_count": 0,
                "convective_fraction": 0.7,
            },
        },
        "heat_losses_recovered": True,
        "distribution_loss_recovery": 90,
        "simplified_approach": 80,
        "distribution_aux_recovery": 80,
        "distribution_aux_power": 30,
        "distribution_loss_coeff": 48,
        "distribution_operation_time": 1,
        "distribution_calculation_mode": "analytical",
        "distribution_15316_3_config": {
            "time_step_hours": 1.0,
            "demand_unit": "kWh",
            "heating": {
                "operation_mode": "demand",
                "nominal_power_kW": 15.0,
                "design_flow_m3_h": 1.304,
                "design_deltaT_K": 10.0,
                "pipe_sections": [
                    {
                        "length_m": 12.0,
                        "equivalent_length_m": 2.0,
                        "linear_thermal_transmittance_W_mK": 0.45,
                        "ambient_temperature_C": 20.0,
                        "recoverable": True,
                    }
                ],
                "pump_control_code": 4,
                "eei": 0.23,
                "hydraulic_correction_factor": 1.0,
                "recoverable_aux_fraction": 0.25,
                "pressure_loss_per_m_kPa": 0.10,
                "additional_pressure_kPa": 0.0,
                "resistance_ratio": 0.30,
                "pump_selection_factor": 1.0,
                "pump_label_power_kW": 0.0,
                "part_load_mode": "load",
            },
            "dhw": {
                "operation_mode": "demand",
                "nominal_power_kW": 15.0,
                "design_flow_m3_h": 1.304,
                "design_deltaT_K": 10.0,
                "dhw_temperature_C": 55.0,
                "dhw_return_deltaT_K": 5.0,
                "max_length_m": 25.0,
                "pressure_loss_per_m_kPa": 0.10,
                "additional_pressure_kPa": 0.0,
                "resistance_ratio": 0.30,
                "pump_control_code": 4,
                "eei": 0.23,
                "hydraulic_correction_factor": 1.0,
                "recoverable_aux_fraction": 0.25,
                "pipe_sections": [
                    {
                        "length_m": 12.0,
                        "equivalent_length_m": 2.0,
                        "linear_thermal_transmittance_W_mK": 0.45,
                        "ambient_temperature_C": 20.0,
                        "recoverable": True,
                    }
                ],
            },
        },
        "same_generator_for_heating_and_dhw": True,
        "dhw_storage_enabled": True,
        "dhw_storage_config": {
            "time_step_hours": 1.0,
            "demand_unit": "kWh",
            "dhw": {
                "enabled": True,
                "storage_volume_l": 180.0,
                "storage_setpoint_C": 55.0,
                "output_temperature_C": 55.0,
                "ambient_temperature_C": 20.0,
                "standby_loss_kWh_per_day_ref": 0.90,
                "standby_set_temperature_ref_C": 55.0,
                "standby_ambient_temperature_ref_C": 20.0,
                "standby_loss_adaptation_factor": 1.0,
                "connection_loss_factor": 1.0,
                "thermal_loss_room_fraction": 0.75,
                "auxiliary_to_medium_fraction": 0.25,
                "input_pump_power_kW": 0.0,
                "input_pump_flow_m3_h": 0.0,
                "input_pump_deltaT_K": 10.0,
                "output_pump_power_kW": 0.0,
                "output_pump_flow_m3_h": 0.0,
                "output_pump_deltaT_K": 10.0,
                "operation_mode": "demand",
            },
        },
        "dhw_generator_config": {
            "nominal_power_kW": 8.0,
            "rated_power_kW": 8.0,
            "boiler_type": "condensing",
            "fuel_type": "natural_gas",
            "boiler_location": "inside_heated",
        },
        "full_load_power": 27,
        "max_monthly_load_factor": 100,
        "tH_gen_i_ON": 1,
        "auxiliary_power_generator": 0,
        "fraction_of_auxiliary_power_generator": 40,
        "generator_circuit": "independent",
        "gen_flow_temp_control_type": "Type A - Based on outdoor temperature",
        "gen_outdoor_temp_data": pd.DataFrame({
            "θext_min_gen": [-7],
            "θext_max_gen": [15],
            "θflw_gen_max": [60],
            "θflw_gen_min": [35],
        }, index=["Generator curve"]),
        "speed_control_generator_pump": "variable",
        "generator_nominal_deltaT": 20,
        "heating_generator_type": "boiler_15316_4_1", #heat_pump_15316_4_2
        "generation_calculation_mode": "boiler_15316_4_1", #heat_pump_15316_4_2
        "boiler_generation_config": {
            "boiler_type": "condensing",
            "fuel_type": "natural_gas",
            "rated_power_kW": 27.0,
            "intermediate_load_fraction": 0.30,
            "eta_Pn_test_pct": 98.0,
            "eta_Pint_test_pct": 106.0,
            "theta_test_Pn_C": 60.0,
            "theta_test_Pint_C": 40.0,
            "f_corr_pct_per_K": 0.04,
            "P_gen_ls_P0_W": 100.0,
            "P_aux_on_W": 80.0,
            "P_aux_off_W": 5.0,
            "f_jacket": 0.40,
            "f_location": 1.0,
            "f_aux_recoverable": 0.75,
            "dew_point_C": 55.0,
            "condensing_gain_pct": 11.0,
            "efficiency_table": {"condensing": {"eta_Pn_test_pct": 98.0, "eta_Pint_test_pct": 106.0, "theta_test_Pn_C": 60.0, "theta_test_Pint_C": 40.0}},
            "loss_table": {"condensing": {"P_gen_ls_P0_W": 100.0}},
            "boiler_location": "inside_heated",
        },
        "heating_heat_pump_15316_4_2_config": {
            "source_type": "air",
            "demand_unit": "kWh",
            "bin_width_C": 1.0,
            "design_outdoor_temperature_C": -7.0,
            "heating_cutoff_temperature_C": 16.0,
            "heating_sink_temp_at_design_C": 45.0,
            "heating_sink_temp_at_cutoff_C": 30.0,
            "heating_deltaT_K": 5.0,
            "hp_operating_limit_C": 55.0,
            "backup_mode": "parallel",
            "heating_backup_efficiency": 1.0,
            "external_auxiliary_power_W": 120.0,
            "standby_power_W": 8.0,
            "heating_storage_loss_kWh_per_day": 0.0,
            "dhw_storage_loss_kWh_per_day": 0.0,
            "storage_test_deltaT_K": 45.0,
            "storage_ambient_temperature_C": 20.0,
            "part_load_performance_method": "simple",
        },
        "efficiency_model": "simple",
        "calc_when_QH_positive_only": False,
        "off_compute_mode": "full",
    }


def get_example_cooling_input() -> dict:
    return {
        "enabled": True,
        "cooling_storage_enabled": True,
        "cooling_system_16798_9_config": {
            "demand_unit": "kWh",
            "system_type": "water",
            "generator_temperature_control": "VARIABLE",
            "distribution_temperature_control": "CONST",
            "distribution_flow_control": "VARIABLE",
            "theta_C_gen_out_set_C": 7.0,
            "theta_C_dis_flw_set_C": 7.0,
            "theta_C_dis_flw_set_min_C": 6.0,
            "theta_C_dis_flw_set_max_C": 18.0,
            "outdoor_compensation_slope": 0.0,
            "outdoor_compensation_offset_K": 7.0,
            "design_deltaT_K": 5.0,
            "design_cooling_load_kW": 12.0,
            "f_wat_C_aux_dis": 0.25,
            "f_C_ls_dis": 0.03,
            "f_C_aux_dis": 0.02,
        },
        "cooling_storage_16798_15_config": {
            "demand_unit": "kWh",
            "storage_type": "STO_TYPE_CW",
            "location": "NC",
            "storage_volume_l": 100.0,
            "storage_temperature_C": 7.0,
            "storage_output_temperature_C": 7.0,
            "storage_return_temperature_C": 12.0,
            "generator_outlet_temperature_C": 7.0,
            "ambient_temperature_C": 20.0,
            "H_C_sto_tot_ls_W_K": 1.0,
            "generator_loop_loss_coefficient_W_K": 0.3,
            "distribution_loop_loss_coefficient_W_K": 0.3,
            "thermal_loss_recoverable_fraction": 0.0,
            "auxiliary_loss_recoverable_fraction": 0.75,
            "auxiliary_to_medium_fraction": 1.0,
            "input_pump_power_kW": 0.020,
            "input_pump_flow_m3_h": 1.0,
            "input_pump_deltaT_K": 5.0,
            "output_pump_power_kW": 0.020,
            "output_pump_flow_m3_h": 1.0,
            "output_pump_deltaT_K": 5.0,
        },
        "cooling_generation_16798_13_config": {
            "demand_unit": "kWh",
            "nominal_capacity_kW": 12.0,
            "generation_type": "COMP",
            "heat_rejection_type": "AIR_C_COND",
            "theta_C_gen_out_limit_C": 5.0,
            "theta_C_gen_out_set_C": 7.0,
            "free_cooling_enabled": False,
            "performance_includes_heat_rejection_aux": True,
            "control_power_kW": 0.010,
            "additional_auxiliary_power_kW": 0.0,
            "heat_recovery_fraction": 0.0,
            "minimum_part_load_ratio": 0.0,
            "part_load_performance_method": "simple",
        },
    }
